/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lluvia;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Enyerson
 */
public class Ventana extends javax.swing.JPanel {
    int cant=100;//cantidad de lluvia
    int velocidad=10;//velocidad de la lluvia de 1-10 velocidades recomendadas
    ArrayList<gota> rain =new ArrayList();
//    gota gotica;
    static JFrame jf;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
//        gotica=new gota(300);
       
        
    }

  
    
    public static void main(String[] arg ){
        jf=new JFrame();
     
        
        jf.setVisible(true);
        jf.setSize(500, 500);
        Ventana v=new Ventana();
        jf.add(v);
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        v.CrearLluvia(v.cant);
        while (true) {       
            //v.moveGota();
            
            //v.repaint();
            jf.repaint();
            try {
                Thread.sleep(100/v.velocidad);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

public void CrearLluvia(int cant){
    for (int i = 0; i < cant; i++) {
        this.rain.add(new gota(jf.getWidth()));
        
    }
}

@Override
    public void paint(Graphics g) {
		super.paint(g);
		Graphics2D g2d = (Graphics2D) g;
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
				RenderingHints.VALUE_ANTIALIAS_ON);
		//g2d.fillOval(x ,y, 3, 3);
               // gotica.moverGota();
               g2d.setColor(Color.BLUE);
               for(gota a:rain){
                   a.gotas(g);
               }
//                gotica.gotas(g);
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
